services:
  postgres:
    image: postgres:18-alpine
    container_name: nuxt-net-monitoring-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: net-monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net-monitoring

  # Nuxt Network Monitoring Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-net-monitoring-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    environment:
      # Override DB_HOST to use the postgres service name
      NUXT_DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - net-monitoring
volumes:
  postgres_data:
    driver: local

networks:
  net-monitoring:
    driver: bridge
