services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: nuxt-net-monitoring-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: net-monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net-monitoring

  # Nuxt Network Monitoring Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-net-monitoring-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # SNMP Configuration - Update these values
      NUXT_SNMP_COMMUNITY: hello@world  # CHANGE THIS!
      NUXT_SNMP_HOST: 192.168.1.1       # Your router/PfSense IP
      NUXT_SNMP_IN_OID: 1.3.6.1.2.1.2.2.1.10.5
      NUXT_SNMP_OUT_OID: 1.3.6.1.2.1.2.2.1.16.5
      
      # Ping Target
      NUXT_PING_HOST: 8.8.8.8
      
      # PostgreSQL Database (connects to postgres service)
      NUXT_DB_HOST: postgres
      NUXT_DB_PORT: 5432
      NUXT_DB_USER: postgres
      NUXT_DB_PASSWORD: postgres
      NUXT_DB_NAME: net-monitor
      
      # Basic Authentication - CHANGE THESE DEFAULTS!
      NUXT_USER: admin        # CHANGE THIS!
      NUXT_PASS: secret123    # CHANGE THIS!
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - net-monitoring
    # Use host network mode if you need to access local network devices
    # network_mode: host

volumes:
  postgres_data:
    driver: local

networks:
  net-monitoring:
    driver: bridge
